application:
  name: @project.name@
  title: TDS Spring Boot
  organization: Technical Development Solutions
  version: @project.version@
  buildNumber: @buildNumber@
  buildDateTime: @timestamp@

swagger:
  title: TDS Spring Boot
  description: TODO
  tos:
    url: TODO
  contact:
    name: TODO
    url: TODO
    email: TODO
  api:
    license:
      url: TODO

server:
  port: 80
  error:
    whitelabel:
      enabled: false


spring:
  profiles:
    active: dev
  autoconfigure:
    exclude:
      org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, \
      org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration, \
      org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

security:
  custom:
    system: custom
    admin:
      password: password
    user:
      password: password

logging:
  level:
    ROOT: info

#spring.datasource.url: jdbc:mysql://ubuntu-filekit-01:3306/seed
#spring.datasource.username: chris
#spring.datasource.password: abcABC123!@#
#spring.datasource.driver-class-name: com.mysql.jdbc.Driver

#elasticsearch:
#  host: ${ELASTICSEARCH_HOST:localhost}
#  port: 9200
#  protocol: https
#  username: ${ELASTICSEARCH_USERNAME:elastic}
#  password: ${ELASTICSEARCH_PASSWORD:iq3KFXPsMm4OlaWnB9am}
#  certificatePath: ${ELASTICSEARCH_CERTPATH:C:\Users\Chris\Dropbox\Github\tds\tds-docker-elasticsearch\certs\elasticsearch-01\elasticsearch-01.crt}

