application.name: @project.name@
application.title: TDS Spring Boot
application.organization: Technical Development Solutions
application.version: @project.version@
application.buildNumber: @buildNumber@
application.buildDateTime: @timestamp@

swagger.title: TDS Spring Boot
swagger.description: Description TODO...
swagger.tos.url: http://todo.com
swagger.contact.name: Contact name TODO...
swagger.contact.url: http://todo.com
swagger.contact.email: todo@todo.com
swagger.api.license: License TODO...
swagger.api.license.url: http://todo.com

security.custom.system: custom
security.custom.admin.password: password
security.custom.user.password: password

#logging.pattern.console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(18971){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
logging.level.ROOT: info
logging.level.com.techdevsolutions: debug

#spring.datasource.url: jdbc:mysql://ubuntu-filekit-01:3306/seed
#spring.datasource.username: chris
#spring.datasource.password: abcABC123!@#
#spring.datasource.driver-class-name: com.mysql.jdbc.Driver

#elasticsearch.host: localhost
#elasticsearch.username: elastic
#elasticsearch.password: O15IYlLhFF3ok17QPEhi