application.name: @project.name@
application.title: TDS Spring Boot
application.organization: Technical Development Solutions
application.version: @project.version@
#application.buildNumber: @buildNumber@
application.buildDateTime: @timestamp@

swagger.title: TDS Spring Boot
swagger.description: TODO...
swagger.tos: TODO...
swagger.tos.url: TODO...
swagger.contact.name: TODO...
swagger.contact.url: TODO...
swagger.contact.email: TODO...
swagger.api.license: TODO...
swagger.api.license.url: TODO...

#spring.datasource.url: jdbc:mysql://ubuntu-filekit-01:3306/seed
#spring.datasource.username: chris
#spring.datasource.password: abcABC123!@#
#spring.datasource.driver-class-name: com.mysql.jdbc.Driver

#elasticsearch.host: localhost
#elasticsearch.username: elastic
#elasticsearch.password: O15IYlLhFF3ok17QPEhi